### ISSUE TITLE
.mobi support? 

### ISSUE THREAD

**Issue by simonmysun** [chusiang/working-on-gnu-linux#23]
And also other eBook format support. 

http://help.gitbook.com/format/output.html

**Comment by chusiang** [comment]
You can find it with keyword of **MOBI (for Kindle)**. 
- http://chusiang.gitbooks.io/working-on-gnu-linux

**Comment by simonmysun** [comment]
Oh! I'm so sorry to disturb you. 

Thank you very much!

**Comment by chusiang** [comment]
You're welcome.

Enjoy it!
