### ISSUE TITLE
PowerTOP 切換鍵爲 TAB / SHIFT+TAB

### ISSUE THREAD

**Issue by theJian** [chusiang/working-on-gnu-linux#28]
08 電源管理 - PowerTOP

> 請使用方向鍵 ← → 切換至 Tunables 分頁

我的機器上分頁切換鍵爲 `TAB / SHIFT + TAB`
PowerTOP version v2.8 
ArchLinux

**Comment by chusiang** [comment]
Hi @theJian,

在下手邊沒有實體的 Arch Linux，晚點再來開 VM 測了。

感謝您的回報。
