### ISSUE TITLE
29. 檢測硬碟 S.M.A.R.T. 健康狀態 內容錯誤

### ISSUE THREAD

**Issue by Vdragon** [chusiang/working-on-gnu-linux#4]
1. Palimpsest 軟體現已改名為 GNOME Disks  
2. <del>GNOME Disks 維基百科超連結少一個右括弧</del>（目前看起來這是 GitBook 的軟體缺陷，因為括弧是有效的 URL 字元）

**Comment by chusiang** [comment]
謝謝提供新資訊，撰寫文章的時候其套件名稱還叫 palimpsest 啊。

**Comment by chusiang** [comment]
已於 https://github.com/chusiang/working-on-gnu-linux/commit/7071658d3b70afb6aac6dc29dd7dca7945211803 和 https://github.com/chusiang/working-on-gnu-linux/commit/2f999046eed32e53072e973ac36031f760f606dc 中修正。
